// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMVC_EF_NparaN.DAL;

#nullable disable

namespace ProjetoMVC_EF_NparaN.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240911135732_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CursoEstudante", b =>
                {
                    b.Property<int>("CursosCursoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudantesEstudanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CursosCursoID", "EstudantesEstudanteId");

                    b.HasIndex("EstudantesEstudanteId");

                    b.ToTable("EstudantesCursos", (string)null);
                });

            modelBuilder.Entity("ProjetoMVC_EF_NparaN.Models.Curso", b =>
                {
                    b.Property<int>("CursoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CursoID");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("ProjetoMVC_EF_NparaN.Models.Estudante", b =>
                {
                    b.Property<int>("EstudanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EstudanteId");

                    b.ToTable("Estudantes");
                });

            modelBuilder.Entity("CursoEstudante", b =>
                {
                    b.HasOne("ProjetoMVC_EF_NparaN.Models.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursosCursoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoMVC_EF_NparaN.Models.Estudante", null)
                        .WithMany()
                        .HasForeignKey("EstudantesEstudanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
