// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMVC_EF_NparaN.DAL;

#nullable disable

namespace ProjetoMVC_EF_NparaN.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240912111139_adicionandoIDEstudantesCursos2")]
    partial class adicionandoIDEstudantesCursos2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ProjetoMVC_EF_NparaN.Models.Curso", b =>
                {
                    b.Property<int>("CursoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CursoID");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("ProjetoMVC_EF_NparaN.Models.Estudante", b =>
                {
                    b.Property<int>("EstudanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EstudanteId");

                    b.ToTable("Estudantes");
                });

            modelBuilder.Entity("ProjetoMVC_EF_NparaN.Models.EstudantesCursos", b =>
                {
                    b.Property<int>("EstudanteID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudantesCursosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstudanteID", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("EstudantesCursos");
                });

            modelBuilder.Entity("ProjetoMVC_EF_NparaN.Models.EstudantesCursos", b =>
                {
                    b.HasOne("ProjetoMVC_EF_NparaN.Models.Curso", "Curso")
                        .WithMany("EstudantesCursos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoMVC_EF_NparaN.Models.Estudante", "Estudante")
                        .WithMany("EstudantesCursos")
                        .HasForeignKey("EstudanteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudante");
                });

            modelBuilder.Entity("ProjetoMVC_EF_NparaN.Models.Curso", b =>
                {
                    b.Navigation("EstudantesCursos");
                });

            modelBuilder.Entity("ProjetoMVC_EF_NparaN.Models.Estudante", b =>
                {
                    b.Navigation("EstudantesCursos");
                });
#pragma warning restore 612, 618
        }
    }
}
